name: Generate and upload static website
run-name: Create static output and upload it to Neocities
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - run: pip install pelican
      - name: Generate content
        env:
          SITE_URL: ${{vars.SITE_URL}}
        run: pelican content
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v3
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          neocities_supporter: true # set this to true if you have a supporter account and want to bypass unsuported files filter.
          preview_before_deploy: true # print a deployment plan prior to waiting for files to upload.
          dist_dir: output
